### ISSUE TITLE
this is amazing work

### ISSUE THREAD

**Issue by jpritikin** [AztecProtocol/AZTEC#1]
I encourage you to apply for grants from MakerDAO and the Ethereum Foundation.

**Comment by ArnSch** [comment]
Thank you Joshua! Closing this issue just to keep things clean, but appreciate your comment :) 

We'll be sending updates over the next weeks/months (things like the proof generation api, and a spec for a decentralised exchange built on top of AZTEC). You should get notifications on here, but you can also sign up on aztecprotocol.com
