### ISSUE TITLE
The links to the whitepaper are outdated

### ISSUE THREAD

**Issue by elopio** [AztecProtocol/AZTEC#19]
On the website and the README, you mention that the whitepaper can be found in
https://github.com/AztecProtocol/AZTEC/blob/master/AZTEC.pdf

That link is 404.

**Comment by ArnSch** [comment]
Thanks @elopio, fixing now

**Comment by PaulRBerg** [comment]
Fixed in https://github.com/AztecProtocol/AZTEC/pull/20
