### ISSUE TITLE
BN128 is not the curve that ZCash uses in Sapling

### ISSUE THREAD

**Issue by tuxxy** [AztecProtocol/AZTEC#2]
Hi guys, really exciting work here!

I was looking over the paper and I saw that you referred to ZCash using the BN128 curve, but this is a tad outdated.

ZCash switched to BLS12-381, a curve constructed by Sean Bowe (https://z.cash/blog/new-snark-curve).

This was formally switched in Sapling, so unfortunately this statement is no longer true. Here is the Pull Request and discussion of this switch: https://github.com/zcash/zcash/issues/2502

**Comment by ArnSch** [comment]
Hey! Thanks for the spotting this, that section of the paper was written quite a while back. Will edit in a bit.

**Comment by zac-williamson** [comment]
Thanks for pointing that out, I've updated the paper to reflect this change; closing as a result.
