### ISSUE TITLE
Expand on gas costs

### ISSUE THREAD

**Issue by WyseNynja** [AztecProtocol/AZTEC#7]
The README mentions that the gas cost is approximately 900,000 gas. It would be helpful if there were some comparisons to other transactions. Maybe compare to a standard ETH transfer (21,000, 42.9x) and a standard DAI transfer.

**Comment by zac-williamson** [comment]
> How common will 1 input, 1 output notes actually be though? I feel like 1 or 2 in and 2 out are going to be more common transactions.
> 
> I'm not asking for a free lunch here. I'm simply asking for clear documentation of transaction costs.

1-input 1-output transactions are useful for bilateral trades between different AZTEC compatible assets - we'll be

**Comment by PaulRBerg** [comment]
Following up, 1-input 1-output transactions occur in bilateral trades between different AZTEC notes. Imagine I have a note and I send you all the tokens I have by destroying the note and issuing a new one with a viewing key you know.
