### ISSUE TITLE
Update AZTEC note ABI to include a note type

### ISSUE THREAD

**Issue by zac-williamson** [AztecProtocol/AZTEC#71]
# The problem space  

Currently we only support one type of AZTEC note, an UXTO-style AZTEC commitment. However, over time we will want to support different 'types' of AZTEC note.  

For example, in our short-term roadmap we will be implementing El-Gamal treasury notes. These notes, and others, will need to be able to be distinguished from one another.  

# Solution  

When computing a note's hash, we should integrate a 'type' variable into the hash, with different values mapping to different kinds of AZTEC notes.  

In addition, we should change the note ABI encoding to include the note type. This *shouldn't* be too painful as we don't need to change any ABI encodings for the inputs to our validator contracts (the note type is implicit - a given proof only works with one type of note).  

### Updating the ABI encoding to contain the `noteType`

Old ABI encoding:  

| Offset | Length | Name | Type | Description |  
| --- | --- | --- | --- | --- |  
| 0x00 | 0x20 | owner | uint | owner of note |  
| 0x20 | 0x20 | noteHash | bytes32 | hash of note public key |  
| 0x40 | - | noteData | bytes | public key data + note metadata |  

New ABI encoding:  

| Offset | Length | Name | Type | Description |  
| --- | --- | --- | --- | --- |  
| 0x00 | 0x20 | noteType | uint | type identifier of note |  
| 0x20 | 0x20 | owner | uint | owner of note |  
| 0x40 | 0x20 | noteHash | bytes32 | hash of note public key + noteType |  
| 0x40 | - | noteData | bytes | public key data + note metadata |  

### Work to be done  

1. Update ABI encoding of `JoinSplit` output notes to include `noteType` variable  
1. Update ABI encoding of `BilateralSwap` output notes to include `noteType` variable  
1. Update ABI encoding of `DividendComputation` output notes to include `noteType` variable  
1. Update ABI encoding of `AdjustSupply` output notes to include `noteType` variable  
1. Update `aztec.js` `abiEncoder` module to use `noteType` variable when encoding/decoding notes  

### Initial list of note types  

| NoteType | Name | Description |  
| --- | --- | --- |  
| 1 | UXTO | Standard AZTEC note |  
| 2 | TREASURY | ElGamal treasury note |

**Comment by ArnSch** [comment]
Done in #79
