### ISSUE TITLE
Missing MINT_PROOF in node module

### ISSUE THREAD

**Issue by gbotrel** [AztecProtocol/AZTEC#85]
Pulling @aztec/dev-utils version 2.0.0. Seems node module is missing some constants and code related to confidential minting.

`yarn init && echo 'const {proofs} = require("@aztec/dev-utils");console.log(proofs);' > main.js && yarn add @aztec/dev-utils && node main.js`

*Outputs*: 
`{ JOIN_SPLIT_PROOF: '65793' }`

*Missing*:
 `MINT_PROOF: '66049';    BURN_PROOF: '66305';`

Pulling aztec.js version 0.6.0, 
`node_modules/aztec.js/lib/proof/mint` is missing
`node_modules/aztec.js/lib/proof/burn` is missing

## Your Environment

* AZTEC packages and their versions: 
``` "dependencies": {
    "@aztec/dev-utils": "^2.0.0",
    "aztec.js": "^0.6.0"
  }
```
* Node and npm version: node: v11.13.0, npm: 6.7.0, yarn : 1.15.2

**Comment by PaulRBerg** [comment]
We downgraded version `2.0.0` to be on the `beta` distribution tag. Now master has the latest version of `@aztec/dev-utils`, that is `1.7.0`, which contains all the proofs reported as missing in this issue :)

Tip: make sure to fully clean your node_modules before pulling from master. Sometimes, npm doesn't play nicely.
